apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: configmap-test
data:
  # Configuración con clave crítica faltante (API_KEY eliminada)
  DATABASE_URL: "postgresql://user:password@db.example.com:5432/mydb"
  # API_KEY: "super-secret-api-key-12345"  # <-- Esta línea fue eliminada
  LOG_LEVEL: "INFO"
  FEATURE_FLAG_ENABLED: "true"
  MAX_CONNECTIONS: "100"
  TIMEOUT_SECONDS: "30" 